Repository COSC481W-2024Winter/ResoluteApp, pull requests merged in 2024-03, with the labels that each got.

#37 Update: Multiple Instrument Tests can Be Tested
  .idea/androidTestResultsUserPreferences.xml
  .idea/deploymentTargetDropDown.xml
  app/src/androidTest/java/com/example/resoluteapp/LogExercise_IT.java
Labels: enhancement, sprint 2, pull request

#38 Update: Enhancements To Log Exercise
  app/src/main/java/com/example/resoluteapp/LogExerciseFragment.java
  app/src/main/res/layout/fragment_log_exercise.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, sprint 2, pull request

#39 feat: Viewing friends list
  app/src/androidTest/java/com/example/resoluteapp/Friends_IT.java
  app/src/main/java/com/example/resoluteapp/FriendsFragment.java
  app/src/main/java/com/example/resoluteapp/MainActivity.java
  app/src/main/res/layout/fragment_friends.xml
Labels: feature, sprint 2, ui/ux design, pull request

#40 feat: Password hashing and Login/Registration tests
  app/src/androidTest/java/com/example/resoluteapp/LogIn_IT.java
  app/src/androidTest/java/com/example/resoluteapp/Register_IT.java
  app/src/main/java/com/example/resoluteapp/HomeFragment.java
  app/src/main/java/com/example/resoluteapp/LoginFragment.java
  app/src/main/java/com/example/resoluteapp/MainActivity.java
  app/src/main/java/com/example/resoluteapp/RegisterFragment.java
Labels: enhancement, sprint 2, pull request, Firebase

#51 feat: Removing friends
  app/src/androidTest/java/com/example/resoluteapp/Friends_IT.java
  app/src/main/java/com/example/resoluteapp/FriendsFragment.java
  app/src/main/res/navigation/nav_graph.xml
Labels: enhancement, feature, sprint 2, ui/ux design, pull request
