Repository COSC481W-2024Winter/ResoluteApp, pull requests merged in 2024-04, with the labels that each got.

#62 Jt/inbox exercises
  app/src/androidTest/java/com/example/resoluteapp/LogExercise_IT.java
  app/src/main/java/com/example/resoluteapp/LogExerciseFragment.java
Labels: enhancement, sprint 3, pull request

#63 feat: Viewing replies to a logged exercise
  app/src/androidTest/java/com/example/resoluteapp/Inbox_IT.java
  app/src/androidTest/java/com/example/resoluteapp/PreviousActivity_IT.java
  app/src/androidTest/java/com/example/resoluteapp/Reply_IT.java
  app/src/main/java/com/example/resoluteapp/MainActivity.java
  app/src/main/java/com/example/resoluteapp/PrevActivityFragment.java
  app/src/main/java/com/example/resoluteapp/ReplyFragment.java
  app/src/main/res/layout/fragment_reply.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: enhancement, feature, sprint 3, pull request

#68 feat: Deleting a logged exercise
  app/src/androidTest/java/com/example/resoluteapp/Inbox_IT.java
  app/src/androidTest/java/com/example/resoluteapp/Reply_IT.java
  app/src/main/java/com/example/resoluteapp/InboxFragment.java
  app/src/main/java/com/example/resoluteapp/ReplyFragment.java
  app/src/main/res/layout/fragment_reply.xml
Labels: enhancement, feature, sprint 3, ui/ux design, pull request

#70 fix: Navigation from friends to profile
  app/src/main/res/layout/fragment_friends.xml
Labels: front end bug, pull request

#72 fix: Back-button prevented and misc. changes
  app/src/main/java/com/example/resoluteapp/HomeFragment.java
  app/src/main/java/com/example/resoluteapp/LoginFragment.java
  app/src/main/java/com/example/resoluteapp/MainActivity.java
  app/src/main/res/layout/fragment_friends.xml
  app/src/main/res/layout/fragment_reply.xml
Labels: front end bug, ui/ux design
